version: "3.8"

services:
  jenkins-server:
    build:
      context: ./server
    image: jenkins-server-plasticscm:latest
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=18889"
    hostname: jenkins-server
    volumes:
      - ./server/home:/var/jenkins_home
    expose:
      - 8080
      - 50000
    init: true
    ports:
      - "8080:8080"
      - "50000:50000"
      - "18889:18889"

  jenkins-agent:
    build:
      context: ./slave
    depends_on:
      - "jenkins-server"
    image: jenkins-agent-plasticscm:latest
    command: [
      "-wait",
      "tcp://jenkins-server:8080",
      "-timeout",
      "120s",
      "jenkins-agent",
      "-url",
      "http://jenkins-server:8080",
      "@/run/secrets/agent-secret",
      "single-agent"
    ]
    volumes:
      - ./slave/client-config:/home/jenkins/.plastic4
    init: true
    secrets:
      - agent-secret

secrets:
  agent-secret:
    file: ./slave/secret.txt

